---
name: docker-push
on:
  workflow_call:
    inputs:
      is_pr:
        required: true
        type: boolean

env:
  DOCKER_USERNAME: "${{ secrets.DOCKERHUB_USERNAME }}"
  DOCKER_PASSWORD: "${{ secrets.DOCKERHUB_TOKEN }}"

jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
    - name: ci/checkout-repo
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
    - name: ci/prepare-docker-environment
      uses: ./.github/actions/docker-prepare
    - name: ci/push-image-pr
      run: "make push-image-pr"
      if: "${{ inputs.is_pr }}"
    - name: ci/push-image
      run: "make push-image"
      if: "${{ !inputs.is_pr }}"

  docker-scan:
    runs-on: ubuntu-latest
    needs: docker-push
    if: "${{ !inputs.is_pr }}"
    permissions:
      contents: read
    steps:
    - name: ci/checkout-repo
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
    - name: ci/anchore-scan
      uses: mattermost/actions/delivery/anchore-scan@main
      with:
        image_name: "mattermost/bifrost:${{ github.ref_name }}"
        dockerfile_path: ./build/Dockerfile
        show_vulnerabilities: 'false'
        anchorectl_url: ${{ secrets.ANCHORECTL_URL }}
        anchorectl_username: ${{ secrets.ANCHORECTL_USERNAME }}
        anchorectl_password: ${{ secrets.ANCHORCTL_PASSWORD }}
        ts_oauth_client_id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        ts_oauth_secret: ${{ secrets.TS_OAUTH_SECRET }}