name: cd
on:
  workflow_run:
    workflows: ["ci"]
    types:
    - completed
  push:
    tags:
    - "v**"
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: cd/checkout
      uses: actions/checkout@dc323e67f16fb5f7663d20ff7941f27f5809e9b6 # v3.2.0

    - name: cd/set-tag-pr
      run: |
        echo "IMAGE_TAG=${INCOMING_PR_SHA:0:7}" >> $GITHUB_ENV
      env:
        INCOMING_PR_SHA: ${{ github.event.workflow_run.head_sha }}

    - name: cd/set-tag-push
      if: github.ref_type == 'tag'
      run: echo "IMAGE_TAG=${{ github.ref_name }}" >> $GITHUB_ENV

    - name: cd/setup-buildx
      uses: docker/setup-buildx-action@15c905b16b06416d2086efa066dd8e3a35cc7f98 # v2.4.0

    - name: cd/docker-login
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # v2.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: cd/push-docker
      run: make buildx-image
      env:
        BIFROST_IMAGE_TAG: ${{ env.IMAGE_TAG }}
