---
name: ci
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    uses: ./.github/workflows/.test.yml
  push-docker:
    uses: ./.github/workflows/.docker-push.yml
    with:
      is_pr: "${{ github.ref != 'refs/heads/master' }}"
    secrets: inherit
    needs: [test]
